site_name: MkDocs Site API Test
site_description: MkDocs test site for API course.

theme:
  name: material
  custom_dir: 'overrides'112

nav:
  - Home: index.md
  - About: about.md
  - API Reference: dist/index.html
